feat: support backup configuration setting
honestbank/terraform-gcp-sql pull request #12
Opened 2022-06-26 17:40 UTC by poom

## Pull Request Submission Checklist

Please confirm that you have done the following before requesting reviews:

- [ ] I have confirmed that the PR type is appropriate for the change I am making according to the [Honest Pull Request and Commit Message Naming Conventions](https://www.notion.so/honestbank/Pull-Request-and-Commit-Message-Naming-Conventions-bd97f2cbb34c4c73b1ff3a3e384b850c).
- [ ] I have typed an adequate description that explains **why** I am making this change.
- [ ] I have installed and run standard pre-commit hooks that lints and validates my code.

### Description

* support backup configuration setting

2022-06-27 10:26 UTC, deejiw commented on modules/google_sql_database_instance/variables.tf
> +  default     = "03:00"
where do we specify UTC for `settings_backup_configuration_start_time`

2022-06-27 10:38 UTC, deejiw approved these changes

2022-07-06 08:30 UTC, jai commented on modules/google_sql_database_instance/main.tf
> +#These setting will override from code
```suggestion
# This is a component module - these setting will be overridden from the embedding module/repo.
```

2022-07-06 08:32 UTC, jai requested changes
One small edit to the comment, thanks.

2022-07-07 03:44 UTC, MXfive reviewed
Just Jia's comment, then OK for me, ping again when fixed for a ✅

2022-07-07 05:32 UTC, poom commented on modules/google_sql_database_instance/variables.tf
> +  default     = "03:00"
@deejiw @MXfive fixed

2022-07-07 05:32 UTC, poom commented on modules/google_sql_database_instance/main.tf
> +#These setting will override from code
fixed

2022-07-07 05:59 UTC, MXfive approved these changes

2022-07-08 06:49 UTC, jai approved these changes

2022-07-08 06:50 UTC, merged