feat: support private ip
honestbank/terraform-gcp-sql pull request #2
Opened 2022-03-19 18:03 UTC by poom

# Description

- Support Private IP - It contains 3 modules - `google_compute_global_address`, `google_compute_network`, and `google_service_networking_connection`
- After #1 merged, I will rebase this PR

# Known Issues

- Unit test will open new PR
- Terratest still fail on Github Actions and pass on My Mac 😭

2022-03-21 18:06 UTC, poom commented
terratest log

<details><summary>Show Log</summary>

```log
TestTerraformCreateGCPSQL/create_mysql_with_public_ip 2022-03-22T00:26:48+07:00 logger.go:66:
TestTerraformCreateGCPSQL/create_mysql_with_public_ip 2022-03-22T00:26:48+07:00 logger.go:66: You may now begin working with Terraform. Try running "terraform plan" to see
TestTerraformCreateGCPSQL/create_mysql_with_public_ip 2022-03-22T00:26:48+07:00 logger.go:66: any changes that are required for your infrastructure. All Terraform commands
TestTerraformCreateGCPSQL/create_mysql_with_public_ip 2022-03-22T00:26:48+07:00 logger.go:66: should now work.
TestTerraformCreateGCPSQL/create_mysql_with_public_ip 2022-03-22T00:26:48+07:00 logger.go:66:
TestTerraformCreateGCPSQL/create_mysql_with_public_ip 2022-03-22T00:26:48+07:00 logger.go:66: If you ever set or change modules or backend configuration for Terraform,
TestTerraformCreateGCPSQL/create_mysql_with_public_ip 2022-03-22T00:26:48+07:00 logger.go:66: rerun this command to reinitialize your working directory. If you forget, other
TestTerraformCreateGCPSQL/create_mysql_with_public_ip 2022-03-22T00:26:48+07:00 logger.go:66: commands will detect it and remind you to do so if necessary.
TestTerraformCreateGCPSQL/create_mysql_with_public_ip 2022-03-22T00:26:48+07:00 retry.go:91: terraform [apply -input=false -auto-approve -lock=false]
TestTerraformCreateGCPSQL/create_mysql_with_public_ip 2022-03-22T00:26:48+07:00 logger.go:66: Running command terraform with args [apply -input=false -auto-approve -lock=false]
TestTerraformCreateGCPSQL/create_mysql_with_public_ip 2022-03-22T00:26:51+07:00 logger.go:66:
TestTerraformCreateGCPSQL/create_mysql_with_public_ip 2022-03-22T00:26:51+07:00 logger.go:66: Terraform used the selected providers to generate the following execution
TestTerraformCreateGCPSQL/create_mysql_with_public_ip 2022-03-22T00:26:51+07:00 logger.go:66: plan. Resource actions are indicated with the following symbols:
TestTerraformCreateGCPSQL/create_mysql_with_public_ip 2022-03-22T00:26:51+07:00 logger.go:66:   + create
TestTerraformCreateGCPSQL/create_mysql_with_public_ip 2022-03-22T00:26:51+07:00 logger.go:66:
TestTerraformCreateGCPSQL/create_mysql_with_public_ip 2022-03-22T00:26:51+07:00 logger.go:66: Terraform will perform the following actions:
TestTerraformCreateGCPSQL/create_mysql_with_public_ip 2022-03-22T00:26:51+07:00 logger.go:66:
TestTerraformCreateGCPSQL/create_mysql_with_public_ip 2022-03-22T00:26:51+07:00 logger.go:66:   # random_id.instance_suffix will be created
TestTerraformCreateGCPSQL/create_mysql_with_public_ip 2022-03-22T00:26:51+07:00 logger.go:66:   + resource "random_id" "instance_suffix" {
TestTerraformCreateGCPSQL/create_mysql_with_public_ip 2022-03-22T00:26:51+07:00 logger.go:66:       + b64_std     = (known after apply)
TestTerraformCreateGCPSQL/create_mysql_with_public_ip 2022-03-22T00:26:51+07:00 logger.go:66:       + b64_url     = (known after apply)
TestTerraformCreateGCPSQL/create_mysql_with_public_ip 2022-03-22T00:26:51+07:00 logger.go:66:       + byte_length = 4
TestTerraformCreateGCPSQL/create_mysql_with_public_ip 2022-03-22T00:26:51+07:00 logger.go:66:       + dec         = (known after apply)
TestTerraformCreateGCPSQL/create_mysql_with_public_ip 2022-03-22T00:26:51+07:00 logger.go:66:       + hex         = (known after apply)
TestTerraformCreateGCPSQL/create_mysql_with_public_ip 2022-03-22T00:26:51+07:00 logger.go:66:       + id          = (known after apply)
TestTerraformCreateGCPSQL/create_mysql_with_public_ip 2022-03-22T00:26:51+07:00 logger.go:66:     }
TestTerraformCreateGCPSQL/create_mysql_with_public_ip 2022-03-22T00:26:51+07:00 logger.go:66:
TestTerraformCreateGCPSQL/create_mysql_with_public_ip 2022-03-22T00:26:51+07:00 logger.go:66:   # random_id.random_string will be created
TestTerraformCreateGCPSQL/create_mysql_with_public_ip 2022-03-22T00:26:51+07:00 logger.go:66:   + resource "random_id" "random_string" {
TestTerraformCreateGCPSQL/create_mysql_with_public_ip 2022-03-22T00:26:51+07:00 logger.go:66:       + b64_std     = (known after apply)
TestTerraformCreateGCPSQL/create_mysql_with_public_ip 2022-03-22T00:26:51+07:00 logger.go:66:       + b64_url     = (known after apply)
TestTerraformCreateGCPSQL/create_mysql_with_public_ip 2022-03-22T00:26:51+07:00 logger.go:66:       + byte_length = 12
TestTerraformCreateGCPSQL/create_mysql_with_public_ip 2022-03-22T00:26:51+07:00 logger.go:66:       + dec         = (known after apply)
TestTerraformCreateGCPSQL/create_mysql_with_public_ip 2022-03-22T00:26:51+07:00 logger.go:66:       + hex         = (known after apply)
TestTerraformCreateGCPSQL/create_mysql_with_public_ip 2022-03-22T00:26:51+07:00 logger.go:66:       + id          = (known after apply)
TestTerraformCreateGCPSQL/create_mysql_with_public_ip 2022-03-22T00:26:51+07:00 logger.go:66:     }
TestTerraformCreateGCPSQL/create_mysql_with_public_ip 2022-03-22T00:26:51+07:00 logger.go:66:
TestTerraformCreateGCPSQL/create_mysql_with_public_ip 2022-03-22T00:26:51+07:00 logger.go:66:   # module.test_sql_database_1.google_sql_database.database will be created
TestTerraformCreateGCPSQL/create_mysql_with_public_ip 2022-03-22T00:26:51+07:00 logger.go:66:   + resource "google_sql_database" "database" {
TestTerraformCreateGCPSQL/create_mysql_with_public_ip 2022-03-22T00:26:51+07:00 logger.go:66:       + collation = (known after apply)
TestTerraformCreateGCPSQL/create_mysql_with_public_ip 2022-03-22T00:26:51+07:00 logger.go:66:       + id        = (known after apply)
TestTerraformCreateGCPSQL/create_mysql_with_public_ip 2022-03-22T00:26:51+07:00 logger.go:66:       + instance  = (known after apply)
TestTerraformCreateGCPSQL/create_mysql_with_public_ip 2022-03-22T00:26:51+07:00 logger.go:66:       + name      = "db-first"
TestTerraformCreateGCPSQL/create_mysql_with_public_ip 2022-03-22T00:26:51+07:00 logger.go:66:       + project   = (known after apply)
TestTerraformCreateGCPSQL/create_mysql_with_public_ip 2022-03-22T00:26:51+07:00 logger.go:66:       + self_link = (known after apply)
TestTerraformCreateGCPSQL/create_mysql_with_public_ip 2022-03-22T00:26:51+07:00 logger.go:66:     }
TestTerraformCreateGCPSQL/create_mysql_with_public_ip 2022-03-22T00:26:51+07:00 logger.go:66:
TestTerraformCreateGCPSQL/create_mysql_with_public_ip 2022-03-22T00:26:51+07:00 logger.go:66:   # module.test_sql_database_2.google_sql_database.database will be created
TestTerraformCreateGCPSQL/create_mysql_with_public_ip 2022-03-22T00:26:51+07:00 logger.go:66:   + resource "google_sql_database" "database" {
TestTerraformCreateGCPSQL/create_mysql_with_public_ip 2022-03-22T00:26:51+07:00 logger.go:66:       + collation = (known after apply)
TestTerraformCreateGCPSQL/create_mysql_with_public_ip 2022-03-22T00:26:51+07:00 logger.go:66:       + id        = (known after apply)
TestTerraformCreateGCPSQL/create_mysql_with_public_ip 2022-03-22T00:26:51+07:00 logger.go:66:       + instance  = (known after apply)
TestTerraformCreateGCPSQL/create_mysql_with_public_ip 2022-03-22T00:26:51+07:00 logger.go:66:       + name      = "db-second"
TestTerraformCreateGCPSQL/create_mysql_with_public_ip 2022-03-22T00:26:51+07:00 logger.go:66:       + project   = (known after apply)
TestTerraformCreateGCPSQL/create_mysql_with_public_ip 2022-03-22T00:26:51+07:00 logger.go:66:       + self_link = (known after apply)
TestTerraformCreateGCPSQL/create_mysql_with_public_ip 2022-03-22T00:26:51+07:00 logger.go:66:     }
TestTerraformCreateGCPSQL/create_mysql_with_public_ip 2022-03-22T00:26:51+07:00 logger.go:66:
TestTerraformCreateGCPSQL/create_mysql_with_public_ip 2022-03-22T00:26:51+07:00 logger.go:66:   # module.test_sql_database_instance.google_sql_database_instance.instance will be created
TestTerraformCreateGCPSQL/create_mysql_with_public_ip 2022-03-22T00:26:51+07:00 logger.go:66:   + resource "google_sql_database_instance" "instance" {
TestTerraformCreateGCPSQL/create_mysql_with_public_ip 2022-03-22T00:26:51+07:00 logger.go:66:       + connection_name               = (know [...]

2022-03-23 02:35 UTC, maetolay requested changes
Terratest is failing @poom

2022-03-24 15:59 UTC, poom commented
> Terratest is failing @poom

Yes I cannot fix it... can you help me?

2022-03-29 05:58 UTC, poom commented
Merged with #3

2022-03-29 06:45 UTC, closed without merging